version: '3'

services:
  influxdb:
    image: influxdb
    environment:
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8090:8090"
      - "8099:8099"
    volumes:
      - influxdb:/var/lib/influxdb

volumes:
  influxdb:
